site_name: Surrogate Modeling for Urban Regeneration (SMUR)
site_url: https://vip-smur.github.io/wiki/
repo_url: https://github.com/VIP-SMUR/wiki
edit_uri: blob/main/docs/
site_author: Patrick Kastner
site_description: >-
  This is the project page of the Surrogate Modeling for Urban Regeneration (VIP) at Georgia Tech.

theme:
  name: material
  features:
    - search.highlight
    - search.suggest
    - search.share
    #- header.autohide

    - announce.dismiss

    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips

    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

    - search.highlight
    - search.share
    - search.suggest

    - toc.follow
    # - toc.integrate



  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference


extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - tags
  #- optimize

extra:
  tags:
    Mobility: mobility
    Microclimate: microclimate
    Energy: energy
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/VIP-SMUR


markdown_extensions:
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      auto_title: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - footnotes
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets


# Plugins
plugins:
  - tags
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'


  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: false
      #nav_repos:
        #- name: EnergyInBuildings
        #  import_url: https://github.com/VIP-SMUR/Sp24-EnergyInBuildings?branch=main
        #  imports: [/README.md]

nav:
  - Home:
      - Getting started: index.md
      - Get involved: get-involved.md
  - Projects: 
    - Project overview: projects/index.md
    - 24-Sp-Energy: projects/sp24/energy.md
    - 24-Sp-Microclimate: projects/sp24/microclimate.md
    - 24-Sp-Mobility-1: projects/sp24/mobility-1.md
    - 24-Sp-Mobility-2: projects/sp24/mobility-2.md


  - Team: 
    - Student team overview: teams/students.md
  #- FastAPI: EnergyInBuildings/README.md
