site_name: Surrogate Modeling for Urban Regeneration (SMUR)
site_url: https://vip-smur.github.io/wiki/
repo_url: https://github.com/VIP-SMUR/wiki
edit_uri: blob/main/docs/
site_author: Patrick Kastner
site_description: >-
  Project page of the Surrogate Modeling for Urban Regeneration (VIP) at Georgia Tech.

# Copyright
copyright: Copyright &copy; 2023--24 Sustainable Urban Systems Lab. <a href="https://siddharthdasari.com/">Design credits.</a> 

theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.svg
  logo: images/favicon.svg
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: custom
    property: umami
  tags:
    Mobility: mobility
    Microclimate: microclimate
    Energy: energy
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/VIP-SMUR
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Patrick-Kastner
    - icon: fontawesome/brands/google-scholar
      link: https://gscholar.patrickkastner.de/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/patrickkastner/
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0003-4940-341X

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

markdown_extensions:
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      auto_title: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - footnotes
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - markdown_include.include:
      base_path: docs

# Plugins
plugins:
  - include-markdown
  - search
  #- title-casing
  - glightbox
  - git-revision-date-localized:
      type: timeago
      custom_format: "%d. %B %Y"
      timezone: US/Eastern
      locale: en
      fallback_to_build_date: true
      enable_creation_date: true
      #exclude:
      #    - index.md
      enabled: true
      strict: true
  - tags
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - git-authors:
      show_contribution: true
      show_line_count: true
      show_email_address: false
      count_empty_lines: false
      fallback_to_empty: false
      sort_authors_by: name
      authorship_threshold_percent: 1
      #ignore_commits: .git-blame-ignore-revs
      exclude:
        - projects/**.md
        - teams/**.md
        - getting_started.md
        - get-involved.md
        - index.md
        - '!**/InfluenceCurve.ai'
      enabled: true
      enabled_on_serve: false
      strict: true
  - git-committers:
      repository: VIP-SMUR/wiki
      branch: main
      docs_path: docs/

  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
      # if set the docs directory will not be removed when importing docs. When using this with a nav section in an imported repo
      # you must keep the docs directory in the path (e.g., docs/path/to/file.md).
      keep_docs_dir: true
      nav_repos:
        # Fall 2024
        - name: get-involved
          import_url: https://github.com/VIP-SMUR/.github?branch=main
          imports: [/profile/README.md]

        - name: 24Fa-MPONC
          import_url: https://github.com/VIP-SMUR/24Fa-MPONC?branch=main
          imports: [/README.md]
        - name: 24Fa-Neuroarchitecture
          import_url: https://github.com/VIP-SMUR/24Fa-Neuroarchitecture?branch=main
          imports: [/README.md]
        - name: 24Fa-EnergyInBuildings-Res
          import_url: https://github.com/VIP-SMUR/24Fa-EnergyInBuildings-Res?branch=main
          imports: [/README.md]
        - name: 24Fa-EnergyInBuildings-Com
          import_url: https://github.com/VIP-SMUR/24Fa-EnergyInBuildings-Com?branch=main
          imports: [/README.md]
        - name: 24Fa-Microclimate-LSTM-Kriging
          import_url: https://github.com/VIP-SMUR/24Fa-Microclimate-LSTM-Kriging?branch=main
          imports: [/README.md]
        - name: 24Fa-Microclimate-UMCF
          import_url: https://github.com/VIP-SMUR/24Fa-Microclimate-UMCF?branch=main
          imports: [/README.md]
        - name: 24Fa-Mobility-PEI
          import_url: https://github.com/VIP-SMUR/24Fa-Mobility-PEI?branch=main
          imports: [/README.md]
        # - name: TEST
        #  import_url: https://github.com/VIP-SMUR/Test?branch=main
        #  imports: [/README.md]

        # Spring 2024
        - name: 24Sp-EnergyInBuildings
          import_url: https://github.com/VIP-SMUR/24Sp-EnergyInBuildings?branch=main
          imports: [/README.md]
        - name: 24Sp-Microclimate
          import_url: https://github.com/VIP-SMUR/24Sp-Microclimate?branch=main
          imports: [/README.md]
        - name: 24Sp-Mobility-1
          import_url: https://github.com/VIP-SMUR/24Sp-Mobility-1?branch=main
          imports: [/README.md]
        - name: 24Sp-Mobility-2
          import_url: https://github.com/VIP-SMUR/24Sp-Mobility-2?branch=main
          imports: [/README.md]

nav:
  - Home:
      - Getting started: index.md
      - Get involved: get-involved/profile/README.md
  - Projects:
      - Overview: projects/index.md
      - Fall 2024:
          - Projects: projects/24fa/README.md
          - 24-Fa-Neuroarchitecture: 24fa-neuroarchitecture/README.md
          - 24-Fa-MPONC: 24fa-mponc/README.md
          - 24-Fa-Energy-Com: 24fa-energyinbuildings-com/README.md
          - 24-Fa-Energy-Res: 24fa-energyinbuildings-res/README.md
          - 24-Fa-Microclimate-LSTM-Kriging: 24fa-microclimate-lstm-kriging/README.md
          - 24-Fa-Microclimate-UMCF: 24fa-microclimate-umcf/README.md
          - 24-Fa-Mobility-PEI: 24fa-mobility-pei/README.md
          # - Test: test/README.md

      - Spring 2024:
          - Projects: projects/24sp/README.md
          - 24-Sp-Energy: 24sp-energyinbuildings/README.md
          - 24-Sp-Microclimate: 24sp-microclimate/README.md
          - 24-Sp-Mobility-1: 24sp-mobility-1/README.md
          - 24-Sp-Mobility-2: 24sp-mobility-2/README.md

  - Team:
      - Team overview: team.md

  - Activities: 
      - Conferences: activities/conferences.md
      - Class Dinners: activities/dinners.md
