site_name: "mkdocstrings"
site_description: "Automatic documentation from sources, for MkDocs."
site_url: "https://mkdocstrings.github.io/"
repo_url: "https://github.com/mkdocstrings/mkdocstrings"
repo_name: "mkdocstrings/mkdocstrings"
site_dir: "site"
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md, src/mkdocstrings]
copyright: Copyright &copy; 2019 Timothée Mazzucotelli
edit_uri: edit/main/docs/

nav:
- Home:
  - Overview: index.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- Usage:
  - usage/index.md
  - Theming: usage/theming.md
  - Handlers: usage/handlers.md
  - All handlers:
    - Crystal: https://mkdocstrings.github.io/crystal/
    - Python: https://mkdocstrings.github.io/python/
    - Python (Legacy): https://mkdocstrings.github.io/python-legacy/
  - Guides:
    - Recipes: recipes.md
    - Troubleshooting: troubleshooting.md
# defer to gen-files + literate-nav
- API reference:
  - mkdocstrings: reference/
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md
- Insiders:
  - insiders/index.md
  - Getting started:
    - Installation: insiders/installation.md
    - Changelog: insiders/changelog.md
- Author's website: https://pawamoy.github.io/

theme:
  name: material
  logo: logo.svg
  custom_dir: docs/.overrides
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference

extra_css:
- css/style.css
- css/material.css
- css/mkdocstrings.css
- css/insiders.css

markdown_extensions:
- attr_list
- admonition
- callouts
- footnotes
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.details
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- toc:
    permalink: "¤"

plugins:
- search
- markdown-exec
- gen-files:
    scripts:
    - scripts/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.txt
- coverage
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://installer.readthedocs.io/en/stable/objects.inv  # demonstration purpose in the docs
        - https://mkdocstrings.github.io/autorefs/objects.inv
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          heading_level: 1
          merge_init_into_class: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
- git-committers:
    enabled: !ENV [DEPLOY, false]
    repository: mkdocstrings/mkdocstrings
- redirects:
    redirect_maps:
      theming.md: usage/theming.md
      handlers/overview.md: usage/handlers.md
- minify:
    minify_html: !ENV [DEPLOY, false]

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/pawamoy
  - icon: fontawesome/brands/mastodon
    link: https://fosstodon.org/@pawamoy
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/pawamoy
  - icon: fontawesome/brands/gitter
    link: https://gitter.im/mkdocstrings/community
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/mkdocstrings/
